import {Placeholder} from '../util/placeholder';
import {SingleRow} from '../util/table/singleRow';
import {AllRows} from '../util/table/allRows';
import {
  AdvancedCarbonNanotube,
  AdvancedCasimirCrystal,
  AdvancedCrystalSilicon,
  AdvancedDiamond,
  AdvancedParticleContainer,
  AdvancedPhotonCombiner,
  AdvancedSpaceWarper,
  CarbonNanotube,
  CasimirCrystal,
  CircuitBoard,
  CopperIngot,
  CrystalSilicon,
  Deuterium,
  DeuteronFuelRod,
  Diamond,
  DysonSphereComponent,
  ElectricMotor,
  ElectromagneticMatrix,
  ElectromagneticTurbine,
  EnergeticGraphite, EnergyMatrix,
  Foundation,
  FrameMaterial,
  Gear,
  Glass,
  Graphene,
  GravitonLens,
  GravityMatrix,
  HighPuritySilicon,
  HydrogenFuelRod,
  InformationMatrix,
  IronIngot,
  LogisticsDrone, LogisticsVessel,
  Magnet,
  MagneticCoil,
  MicrocrystallineComponent,
  OrganicCrystal,
  ParticleBroadband,
  ParticleContainer,
  PhotonCombiner,
  PlaneFilter,
  PlasmaExciter,
  Plastic,
  Prisma,
  Processor,
  QuantumChip,
  ReinforcedThruster,
  SiliconOreFromStone,
  SmallCarrierRocket,
  SolarSail,
  SpaceWarper,
  Steel,
  Stone,
  StrangeMatter,
  StructureMatrix,
  SulfuricAcid,
  SuperMagneticRing,
  Thruster,
  TitaniumAlloy, TitaniumCrystal,
  TitaniumGlass,
  TitaniumIngot
} from './cat01';
import {AdvancedGraphene} from '../multipleOutputs/advancedGraphene';

export const ComponentsTable: AllRows = {
  name: 'Components',
  singleRows: [
    new SingleRow([
      IronIngot,
      CopperIngot,
      HighPuritySilicon,
      TitaniumIngot,
      Stone,
      EnergeticGraphite,
      new Placeholder(),
      Plastic,
      Graphene,
      new Placeholder(),
      new Placeholder(),
      new Placeholder(),
    ], 1),
    new SingleRow([
      Magnet,
      MagneticCoil,
      CrystalSilicon,
      TitaniumAlloy,
      Glass,
      Diamond,
      new Placeholder(),
      OrganicCrystal,
      AdvancedGraphene,
      HydrogenFuelRod,
      DeuteronFuelRod,
      new Placeholder(),
    ], 2),
    new SingleRow([
      Steel,
      ElectricMotor,
      AdvancedCrystalSilicon,
      TitaniumGlass,
      Prisma,
      AdvancedDiamond,
      new Placeholder(),
      new Placeholder(),
      TitaniumCrystal,
      Thruster,
      ReinforcedThruster,
      StrangeMatter
    ], 3),
    new SingleRow([
      Gear,
      ElectromagneticTurbine,
      SiliconOreFromStone,
      CircuitBoard,
      GravitonLens,
      SulfuricAcid,
      Deuterium,
      PlaneFilter,
      CarbonNanotube,
      LogisticsDrone,
      LogisticsVessel,
      SmallCarrierRocket
    ], 4),
    new SingleRow([
      PlasmaExciter,
      SuperMagneticRing,
      ParticleBroadband,
      Processor,
      CasimirCrystal,
      ParticleContainer,
      SpaceWarper,
      new Placeholder(),
      AdvancedCarbonNanotube,
      SolarSail,
      FrameMaterial,
      DysonSphereComponent
    ], 5),
    new SingleRow([
      PhotonCombiner,
      AdvancedPhotonCombiner,
      MicrocrystallineComponent,
      QuantumChip,
      AdvancedCasimirCrystal,
      AdvancedParticleContainer,
      AdvancedSpaceWarper,
      new Placeholder(),
      new Placeholder(),
      new Placeholder(),
      new Placeholder(),
      new Placeholder(),
    ], 6),
    new SingleRow([
      ElectromagneticMatrix,
      EnergyMatrix,
      StructureMatrix,
      InformationMatrix,
      GravityMatrix,
      new Placeholder(),
      new Placeholder(),
      new Placeholder(),
      new Placeholder(),
      new Placeholder(),
      new Placeholder(),
      Foundation
    ], 7)
  ]
}
